version: '3' 
services:
    postgres:
        image: "postgres"
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    blog-api:
        image: smagham/simple_blog_api_ts-master
        build:
            context: ./
            dockerfile: Dockerfile.prod
        ports:
            - "3000:3000"
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api