-- Drop the tables
DROP TABLE files;
DROP TABLE word_counts;

-- create a table
CREATE TABLE files(line STRING);

-- Load data into the table
LOAD DATA LOCAL INPATH '/root/input.txt' INTO TABLE files;

-- count number of words and save them in word_counts
CREATE TABLE word_counts AS
SELECT word, count(1) AS count FROM
(SELECT EXPLODE(SPLIT(line, ' ')) AS word FROM files) w
GROUP BY word
ORDER BY count DESC;
