apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
      - name: blog-api
        image: axelsilverdew/simple_blog_api_ts-master
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_HOST
          value: postgres-cluster-ip-service
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USERNAME
          value: postgres
        - name: POSTGRES_DATABASE
          value: simple_blog_api_ts-master
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: POSTGRES_PASSWORD

# TODO: Add Env Vars for Postgres
